// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: proxyman.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddUserOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserOperation) Reset() {
	*x = AddUserOperation{}
	mi := &file_proxyman_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserOperation) ProtoMessage() {}

func (x *AddUserOperation) ProtoReflect() protoreflect.Message {
	mi := &file_proxyman_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserOperation.ProtoReflect.Descriptor instead.
func (*AddUserOperation) Descriptor() ([]byte, []int) {
	return file_proxyman_proto_rawDescGZIP(), []int{0}
}

func (x *AddUserOperation) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type RemoveUserOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserOperation) Reset() {
	*x = RemoveUserOperation{}
	mi := &file_proxyman_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserOperation) ProtoMessage() {}

func (x *RemoveUserOperation) ProtoReflect() protoreflect.Message {
	mi := &file_proxyman_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserOperation.ProtoReflect.Descriptor instead.
func (*RemoveUserOperation) Descriptor() ([]byte, []int) {
	return file_proxyman_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveUserOperation) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type AlterInboundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Operation     *TypedMessage          `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlterInboundRequest) Reset() {
	*x = AlterInboundRequest{}
	mi := &file_proxyman_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlterInboundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterInboundRequest) ProtoMessage() {}

func (x *AlterInboundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxyman_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterInboundRequest.ProtoReflect.Descriptor instead.
func (*AlterInboundRequest) Descriptor() ([]byte, []int) {
	return file_proxyman_proto_rawDescGZIP(), []int{2}
}

func (x *AlterInboundRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *AlterInboundRequest) GetOperation() *TypedMessage {
	if x != nil {
		return x.Operation
	}
	return nil
}

type AlterInboundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlterInboundResponse) Reset() {
	*x = AlterInboundResponse{}
	mi := &file_proxyman_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlterInboundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterInboundResponse) ProtoMessage() {}

func (x *AlterInboundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proxyman_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterInboundResponse.ProtoReflect.Descriptor instead.
func (*AlterInboundResponse) Descriptor() ([]byte, []int) {
	return file_proxyman_proto_rawDescGZIP(), []int{3}
}

var File_proxyman_proto protoreflect.FileDescriptor

const file_proxyman_proto_rawDesc = "" +
	"\n" +
	"\x0eproxyman.proto\x12\x13xray.panel.proxyman\x1a\fserial.proto\x1a\x0eprotocol.proto\"A\n" +
	"\x10AddUserOperation\x12-\n" +
	"\x04user\x18\x01 \x01(\v2\x19.xray.panel.protocol.UserR\x04user\"+\n" +
	"\x13RemoveUserOperation\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"f\n" +
	"\x13AlterInboundRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12=\n" +
	"\toperation\x18\x02 \x01(\v2\x1f.xray.panel.serial.TypedMessageR\toperation\"\x16\n" +
	"\x14AlterInboundResponse2u\n" +
	"\x0eHandlerService\x12c\n" +
	"\fAlterInbound\x12(.xray.panel.proxyman.AlterInboundRequest\x1a).xray.panel.proxyman.AlterInboundResponseB)Z'panel/internal/adapter/xray/proto;protob\x06proto3"

var (
	file_proxyman_proto_rawDescOnce sync.Once
	file_proxyman_proto_rawDescData []byte
)

func file_proxyman_proto_rawDescGZIP() []byte {
	file_proxyman_proto_rawDescOnce.Do(func() {
		file_proxyman_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxyman_proto_rawDesc), len(file_proxyman_proto_rawDesc)))
	})
	return file_proxyman_proto_rawDescData
}

var file_proxyman_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proxyman_proto_goTypes = []any{
	(*AddUserOperation)(nil),     // 0: xray.panel.proxyman.AddUserOperation
	(*RemoveUserOperation)(nil),  // 1: xray.panel.proxyman.RemoveUserOperation
	(*AlterInboundRequest)(nil),  // 2: xray.panel.proxyman.AlterInboundRequest
	(*AlterInboundResponse)(nil), // 3: xray.panel.proxyman.AlterInboundResponse
	(*User)(nil),                 // 4: xray.panel.protocol.User
	(*TypedMessage)(nil),         // 5: xray.panel.serial.TypedMessage
}
var file_proxyman_proto_depIdxs = []int32{
	4, // 0: xray.panel.proxyman.AddUserOperation.user:type_name -> xray.panel.protocol.User
	5, // 1: xray.panel.proxyman.AlterInboundRequest.operation:type_name -> xray.panel.serial.TypedMessage
	2, // 2: xray.panel.proxyman.HandlerService.AlterInbound:input_type -> xray.panel.proxyman.AlterInboundRequest
	3, // 3: xray.panel.proxyman.HandlerService.AlterInbound:output_type -> xray.panel.proxyman.AlterInboundResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proxyman_proto_init() }
func file_proxyman_proto_init() {
	if File_proxyman_proto != nil {
		return
	}
	file_serial_proto_init()
	file_protocol_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxyman_proto_rawDesc), len(file_proxyman_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proxyman_proto_goTypes,
		DependencyIndexes: file_proxyman_proto_depIdxs,
		MessageInfos:      file_proxyman_proto_msgTypes,
	}.Build()
	File_proxyman_proto = out.File
	file_proxyman_proto_goTypes = nil
	file_proxyman_proto_depIdxs = nil
}
