// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: proxy.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CipherType int32

const (
	CipherType_UNKNOWN            CipherType = 0
	CipherType_AES_128_GCM        CipherType = 5
	CipherType_AES_256_GCM        CipherType = 6
	CipherType_CHACHA20_POLY1305  CipherType = 7
	CipherType_XCHACHA20_POLY1305 CipherType = 8
	CipherType_NONE               CipherType = 9
)

// Enum value maps for CipherType.
var (
	CipherType_name = map[int32]string{
		0: "UNKNOWN",
		5: "AES_128_GCM",
		6: "AES_256_GCM",
		7: "CHACHA20_POLY1305",
		8: "XCHACHA20_POLY1305",
		9: "NONE",
	}
	CipherType_value = map[string]int32{
		"UNKNOWN":            0,
		"AES_128_GCM":        5,
		"AES_256_GCM":        6,
		"CHACHA20_POLY1305":  7,
		"XCHACHA20_POLY1305": 8,
		"NONE":               9,
	}
)

func (x CipherType) Enum() *CipherType {
	p := new(CipherType)
	*p = x
	return p
}

func (x CipherType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CipherType) Descriptor() protoreflect.EnumDescriptor {
	return file_proxy_proto_enumTypes[0].Descriptor()
}

func (CipherType) Type() protoreflect.EnumType {
	return &file_proxy_proto_enumTypes[0]
}

func (x CipherType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CipherType.Descriptor instead.
func (CipherType) EnumDescriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{0}
}

type VLESSAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Flow          string                 `protobuf:"bytes,2,opt,name=flow,proto3" json:"flow,omitempty"`
	Encryption    string                 `protobuf:"bytes,3,opt,name=encryption,proto3" json:"encryption,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VLESSAccount) Reset() {
	*x = VLESSAccount{}
	mi := &file_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VLESSAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VLESSAccount) ProtoMessage() {}

func (x *VLESSAccount) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VLESSAccount.ProtoReflect.Descriptor instead.
func (*VLESSAccount) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *VLESSAccount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VLESSAccount) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

func (x *VLESSAccount) GetEncryption() string {
	if x != nil {
		return x.Encryption
	}
	return ""
}

type VMessAccount struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AlterId          uint32                 `protobuf:"varint,2,opt,name=alter_id,json=alterId,proto3" json:"alter_id,omitempty"`
	SecuritySettings *SecurityConfig        `protobuf:"bytes,3,opt,name=security_settings,json=securitySettings,proto3" json:"security_settings,omitempty"`
	TestsEnabled     string                 `protobuf:"bytes,4,opt,name=tests_enabled,json=testsEnabled,proto3" json:"tests_enabled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VMessAccount) Reset() {
	*x = VMessAccount{}
	mi := &file_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMessAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMessAccount) ProtoMessage() {}

func (x *VMessAccount) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMessAccount.ProtoReflect.Descriptor instead.
func (*VMessAccount) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *VMessAccount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VMessAccount) GetAlterId() uint32 {
	if x != nil {
		return x.AlterId
	}
	return 0
}

func (x *VMessAccount) GetSecuritySettings() *SecurityConfig {
	if x != nil {
		return x.SecuritySettings
	}
	return nil
}

func (x *VMessAccount) GetTestsEnabled() string {
	if x != nil {
		return x.TestsEnabled
	}
	return ""
}

type TrojanAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrojanAccount) Reset() {
	*x = TrojanAccount{}
	mi := &file_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrojanAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrojanAccount) ProtoMessage() {}

func (x *TrojanAccount) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrojanAccount.ProtoReflect.Descriptor instead.
func (*TrojanAccount) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *TrojanAccount) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ShadowsocksAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	CipherType    CipherType             `protobuf:"varint,2,opt,name=cipher_type,json=cipherType,proto3,enum=xray.panel.proxy.CipherType" json:"cipher_type,omitempty"`
	IvCheck       bool                   `protobuf:"varint,3,opt,name=iv_check,json=ivCheck,proto3" json:"iv_check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShadowsocksAccount) Reset() {
	*x = ShadowsocksAccount{}
	mi := &file_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShadowsocksAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShadowsocksAccount) ProtoMessage() {}

func (x *ShadowsocksAccount) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShadowsocksAccount.ProtoReflect.Descriptor instead.
func (*ShadowsocksAccount) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *ShadowsocksAccount) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ShadowsocksAccount) GetCipherType() CipherType {
	if x != nil {
		return x.CipherType
	}
	return CipherType_UNKNOWN
}

func (x *ShadowsocksAccount) GetIvCheck() bool {
	if x != nil {
		return x.IvCheck
	}
	return false
}

var File_proxy_proto protoreflect.FileDescriptor

const file_proxy_proto_rawDesc = "" +
	"\n" +
	"\vproxy.proto\x12\x10xray.panel.proxy\x1a\x0eprotocol.proto\"R\n" +
	"\fVLESSAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04flow\x18\x02 \x01(\tR\x04flow\x12\x1e\n" +
	"\n" +
	"encryption\x18\x03 \x01(\tR\n" +
	"encryption\"\xb0\x01\n" +
	"\fVMessAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\balter_id\x18\x02 \x01(\rR\aalterId\x12P\n" +
	"\x11security_settings\x18\x03 \x01(\v2#.xray.panel.protocol.SecurityConfigR\x10securitySettings\x12#\n" +
	"\rtests_enabled\x18\x04 \x01(\tR\ftestsEnabled\"+\n" +
	"\rTrojanAccount\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"\x8a\x01\n" +
	"\x12ShadowsocksAccount\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12=\n" +
	"\vcipher_type\x18\x02 \x01(\x0e2\x1c.xray.panel.proxy.CipherTypeR\n" +
	"cipherType\x12\x19\n" +
	"\biv_check\x18\x03 \x01(\bR\aivCheck*t\n" +
	"\n" +
	"CipherType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0f\n" +
	"\vAES_128_GCM\x10\x05\x12\x0f\n" +
	"\vAES_256_GCM\x10\x06\x12\x15\n" +
	"\x11CHACHA20_POLY1305\x10\a\x12\x16\n" +
	"\x12XCHACHA20_POLY1305\x10\b\x12\b\n" +
	"\x04NONE\x10\tB)Z'panel/internal/adapter/xray/proto;protob\x06proto3"

var (
	file_proxy_proto_rawDescOnce sync.Once
	file_proxy_proto_rawDescData []byte
)

func file_proxy_proto_rawDescGZIP() []byte {
	file_proxy_proto_rawDescOnce.Do(func() {
		file_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_proto_rawDesc), len(file_proxy_proto_rawDesc)))
	})
	return file_proxy_proto_rawDescData
}

var file_proxy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proxy_proto_goTypes = []any{
	(CipherType)(0),            // 0: xray.panel.proxy.CipherType
	(*VLESSAccount)(nil),       // 1: xray.panel.proxy.VLESSAccount
	(*VMessAccount)(nil),       // 2: xray.panel.proxy.VMessAccount
	(*TrojanAccount)(nil),      // 3: xray.panel.proxy.TrojanAccount
	(*ShadowsocksAccount)(nil), // 4: xray.panel.proxy.ShadowsocksAccount
	(*SecurityConfig)(nil),     // 5: xray.panel.protocol.SecurityConfig
}
var file_proxy_proto_depIdxs = []int32{
	5, // 0: xray.panel.proxy.VMessAccount.security_settings:type_name -> xray.panel.protocol.SecurityConfig
	0, // 1: xray.panel.proxy.ShadowsocksAccount.cipher_type:type_name -> xray.panel.proxy.CipherType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proxy_proto_init() }
func file_proxy_proto_init() {
	if File_proxy_proto != nil {
		return
	}
	file_protocol_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_proto_rawDesc), len(file_proxy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_proto_goTypes,
		DependencyIndexes: file_proxy_proto_depIdxs,
		EnumInfos:         file_proxy_proto_enumTypes,
		MessageInfos:      file_proxy_proto_msgTypes,
	}.Build()
	File_proxy_proto = out.File
	file_proxy_proto_goTypes = nil
	file_proxy_proto_depIdxs = nil
}
